### ISSUE TITLE
" QXcbConnection could not connect to display" error appears during "template_diagnosis" Node

### ISSUE THREAD

**Issue by The-Archon-AI** [CoBrALab/RABIES#111]
**Describe the bug**
While running RABIES, the execution will stop at the "template_diagnosis" Node and display the following error: 

`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :1
Could not connect to any X display.`

**Describe RABIES call**
`sudo singularity run -B /home/diegoe/Documents/MRI:/inputs:ro \
-B /home/diegoe/Documents/preproc:/outputs/ \
/home/diegoe/singularity/rabies.sif  preprocess /inputs /outputs `

**Attach log file**
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/6031294/rabies_preprocess.log)

**Attach QC_report**

[QC_report.zip](https://github.com/CoBrALab/RABIES/files/6031297/QC_report.zip)

**Additional context**
I believe this is can be solved by adding the xvfb library to the RABIES container. I also tried running both roscore and rviz simultaneously to no avail. This issue appeared on the 0.2.1 version of RABIES.

**Comment by gdevenyi** [comment]
@Gab-D-G What is trying to open an X window, shouldn't this all be headless?

**Comment by gdevenyi** [comment]
This looks like some kind of issue with matplotlib, the solution appears instead to be, 
https://github.com/ipython/ipython/issues/10627

**Comment by gdevenyi** [comment]
Either that, we explicitly set the backend for matplotlib.

**Comment by gdevenyi** [comment]
The log you attached contains many errors not related to the point you have above
```
     63 2021-02-23 13:01:00,637 - INFO - [Node] Running "slice_timing_correction" ("nipype.interfaces.utility.wrappers.Function")
     64 2021-02-23 13:01:00,709 - WARNING - [Node] Error on "main_wf.bold_main_wf.bold_stc_wf.slice_timing_correction" (/outputs/main_wf/bold_main_wf/bold_stc_wf/_scan_info_subject_id3.sessionT3_split_name_sub-3_ses-T3_T1w/_run_2/slice_timing_correction)
     65 2021-02-23 13:01:00,710 - ERROR - Node slice_timing_correction.a0.a1 failed to run on host pop-os.
     66 2021-02-23 13:01:00,712 - ERROR - Saving crash info to /root/crash-20210223-130100-root-slice_timing_correction.a0.a1-ec163f26-6ddd-4134-9dfa-89b23fbd8dea.pklz
     67 Traceback (most recent call last):
     68   File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
     69     node.run(updatehash=updatehash)
     70   File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
     71     result = self._run_interface(execute=True)
     72   File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
     73     return self._run_command(execute)
     74   File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
     75     result = self._interface.run(cwd=outdir)
     76   File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
     77     runtime = self._run_interface(runtime)
     78   File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
     79     out = function_handle(**args)
     80   File "<string>", line 42, in slice_timing_correction
     81   File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 8876, in ReadImage
     82     return _SimpleITK.ReadImage(*args)
     83 RuntimeError: Exception thrown in SimpleITK ReadImage: ../../Code/IO/src/sitkImageReaderBase.cxx:99:
     84 sitk::ERROR: The file "/rabies_out/main_wf/_scan_info_subject_id3.sessionT3_split_name_sub-3_ses-T3_T1w/_run_2/bold_convert_to_RAS/sub-3_ses-T3_task-rest_run-02_bold_RAS.nii.gz" does not exist.
```

**Comment by gdevenyi** [comment]
Closing for lack of further feedback.
