### ISSUE TITLE
Error running confound_regression with ica_aroma

### ISSUE THREAD

**Issue by ChristianNSchmitz** [CoBrALab/RABIES#145]
Dear Grandjean-lab,

we are still working with RABIES and try to apply it to a rat fMRI dataset. As the preprocessing works flawlessly now, we came across an error of the confound_regression part running ica_aroma. The QC-reports (one example animal is attached) of the preprocessing looks fine. However, confound_regression results in an error. Here is an example:

```------------------------------- RUNNING ICA-AROMA -------------------------------
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' ---------------

Step 1) MELODIC
Step 2) Automatic classification of the components
  - *modified version skips commonspace registration
  - computing edge and out masks
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Found 1 file(s)
Found 42 head motion-related components in a total of 48 components.
/home/rabies/RABIES-0.2.1/rabies/conf_reg_pkg/mod_ICA_AROMA/classification_plots.py:78: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure(figsize=[12, 4])
Step 3) Data denoising

----------------------------------- Finished -----------------------------------

210512-10:29:59,864 nipype.workflow INFO:
         [Node] Finished "main_wf.confound_regression_wf2.ica_aroma".
210512-10:29:59,865 nipype.workflow INFO:
         [Node] Setting-up "main_wf.confound_regression_wf2.regress" in "/outputsPreprocess/main_wf/confound_regression_wf2/_scan_info_subject_id3449.session1_split_name_sub-3449_ses-1_T2w/_run_1/regress".
210512-10:29:59,950 nipype.workflow INFO:
         [Node] Running "regress" ("nipype.interfaces.utility.wrappers.Function")
<string>:49: RuntimeWarning: invalid value encountered in true_divide
<string>:66: RuntimeWarning: invalid value encountered in true_divide
<string>:81: RuntimeWarning: Mean of empty slice.
/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
<string>:82: RuntimeWarning: Mean of empty slice.
210512-10:31:16,489 nipype.workflow INFO:
         [Node] Finished "main_wf.confound_regression_wf2.regress".
210512-10:31:16,490 nipype.workflow INFO:
         [Node] Setting-up "main_wf.confound_regression_datasink" in "/outputsPreprocess/main_wf/_scan_info_subject_id3449.session1_split_name_sub-3449_ses-1_T2w/_run_1/confound_regression_datasink".
210512-10:31:16,535 nipype.workflow INFO:
         [Node] Outdated cache found for "main_wf.confound_regression_datasink".
210512-10:31:16,627 nipype.workflow INFO:
         [Node] Running "confound_regression_datasink" ("nipype.interfaces.io.DataSink")
210512-10:32:50,187 nipype.workflow INFO:
         [Node] Finished "main_wf.confound_regression_datasink".
210512-10:32:50,188 nipype.workflow INFO:
         [Node] Setting-up "main_wf.temporal_diagnosis" in "/outputsPreprocess/main_wf/_scan_info_subject_id3449.session1_split_name_sub-3449_ses-1_T2w/_run_1/temporal_diagnosis".
210512-10:32:50,293 nipype.workflow INFO:
         [Node] Cached "main_wf.temporal_diagnosis" - collecting precomputed outputs
210512-10:32:50,294 nipype.workflow INFO:
         [Node] "main_wf.temporal_diagnosis" found cached.
210512-10:32:50,295 nipype.workflow INFO:
         [Node] Setting-up "main_wf.PlotOverlap_Template2Commonspace" in "/outputsPreprocess/main_wf/PlotOverlap_Template2Commonspace".
210512-10:32:50,328 nipype.workflow INFO:
         [Node] Cached "main_wf.PlotOverlap_Template2Commonspace" - collecting precomputed outputs
210512-10:32:50,328 nipype.workflow INFO:
         [Node] "main_wf.PlotOverlap_Template2Commonspace" found cached.
210512-10:32:50,329 nipype.workflow INFO:
         [Node] Setting-up "main_wf.anat_denoising_diagnosis" in "/outputsPreprocess/main_wf/_scan_info_subject_id3449.session1_split_name_sub-3449_ses-1_T2w/anat_denoising_diagnosis".
210512-10:32:50,449 nipype.workflow INFO:
         [Node] Cached "main_wf.anat_denoising_diagnosis" - collecting precomputed outputs
210512-10:32:50,449 nipype.workflow INFO:
         [Node] "main_wf.anat_denoising_diagnosis" found cached.
210512-10:32:50,450 nipype.workflow INFO:
         [Node] Setting-up "main_wf.template_diagnosis" in "/outputsPreprocess/main_wf/template_diagnosis".
210512-10:32:50,470 nipype.workflow INFO:
         [Node] Cached "main_wf.template_diagnosis" - collecting precomputed outputs
210512-10:32:50,471 nipype.workflow INFO:
         [Node] "main_wf.template_diagnosis" found cached.
210512-10:32:50,471 nipype.workflow INFO:
         ***********************************
210512-10:32:50,472 nipype.workflow ERROR:
         could not run node: main_wf.confound_regression_wf2.ica_aroma.a33.a0
210512-10:32:50,472 nipype.workflow INFO:
         crashfile: /tmp/crash-20210511-224740-root-ica_aroma.a33.a0-d1017097-0b17-464c-a13c-24409ab85fa8.pklz
210512-10:32:50,472 nipype.workflow ERROR:
         could not run node: main_wf.confound_regression_wf2.ica_aroma.a28.a0
210512-10:32:50,473 nipype.workflow INFO:
         crashfile: /tmp/crash-20210512-033330-root-ica_aroma.a28.a0-b3e49555-2732-44a4-9764-13b810332e3a.pklz
210512-10:32:50,473 nipype.workflow INFO:
         ***********************************
Traceback (most recent call last):
  File "/home/rabies/RABIES-0.2.1/exec.py", line 13, in <module>
    execute_workflow()
  File "/home/rabies/RABIES-0.2.1/rabies/run_main.py", line 326, in execute_workflow
    'n_procs': opts.local_threads, 'qsub_args': '-pe smp %s' % (str(opts.min_proc))})
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 61, in run
    report_nodes_not_run(notrun)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
```

**RABIES call:**
root@WSLmachine:~# docker run -it --rm -v /mnt/d/PsiAlc/RabiesDir_Schwarz/rawdataBunch/:/rawInputs:ro -v /mnt/d/PsiAlc/Atlas_Schwarz/:/atlas -v /mnt/d/PsiAlc/RabiesDir_Schwarz/derivates/outputPreprocess/:/outputsPreprocess -v /mnt/d/PsiAlc/RabiesDir_Schwarz/derivates/outputConfoundRegression/:/outputsConfoundRegression gabdesgreg/rabies:latest confound_regression /outputsPreprocess /outputsConfoundRegression --run_aroma --wf_name confound_regression_wf

**Log file:**
[rabies_confound_regression.log](https://github.com/CoBrALab/RABIES/files/6472990/rabies_confound_regression.log)

**You can find the QC report of one example animal attached:**
QC_report\Anat2Template
![sub-3549_ses-2_T2w_registration](https://user-images.githubusercontent.com/35763466/118138303-758e5e00-b406-11eb-9afb-f98adddef46e.png)

QC_report\bold_denoising
![sub-3549_ses-2_run-01_task-rest_bold_denoising](https://user-images.githubusercontent.com/35763466/118138317-7921e500-b406-11eb-953e-2de580047fb4.png)

QC_report\EPI2Anat
![sub-3549_ses-2_run-01_task-rest_bold_registration](https://user-images.githubusercontent.com/35763466/118138327-7c1cd580-b406-11eb-8835-a6fb6cb71b74.png)

QC_report\temporal_diagnosis
![sub-3549_ses-2_run-01_task-rest_bold_temporal_diagnosis](https://user-images.githubusercontent.com/35763466/118138387-8a6af180-b406-11eb-9566-3782780d269c.png)

QC_report\Template2Commonspace
![_registration](https://user-images.githubusercontent.com/35763466/118138362-84751080-b406-11eb-8f87-f243424778d7.png)

**Comment by gdevenyi** [comment]
From the logfile:
```
Traceback (most recent call last):
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 12, in exec_ICA_AROMA
FileNotFoundError: [Errno 2] No such file or directory: '/outputsPreprocess/main_wf/confound_regression_wf2/_scan_info_subject_id3546.session2_split_name_sub-3546_ses-2_T2w/_run_1/ica_aroma/aroma_out/denoised_func_data_nonaggr.nii.gz' -> '/outputsPreprocess/main_wf/confound_regression_wf2/_scan_info_subject_id3546.session2_split_name_sub-3546_ses-2_T2w/_run_1/ica_aroma/aroma_out/sub-3546_ses-2_run-01_task-rest_bold_RAS_combined_aroma.nii.gz'
```

**Comment by ChristianNSchmitz** [comment]
Sorry, that log was referring to a second run with different names for the analysis step. Here is the original log as well as a brief copy of the terminal error message:

```2021-05-16 16:20:54,963 - INFO - [Node] Running "ica_aroma" ("nipype.interfaces.utility.wrappers.Function")
2021-05-16 19:53:34,944 - WARNING - [Node] Error on "main_wf.confound_regression_wf.ica_aroma" (/outputsPreprocess/main_wf/confound_regression_wf/_scan_info_subject_id3546.session2_split_name_sub-3546_ses-2_T2w/_run_1/ica_aroma)
2021-05-16 19:53:34,969 - ERROR - Node ica_aroma.a33.a0 failed to run on host 063255b9af50.
2021-05-16 19:53:34,975 - ERROR - Saving crash info to /tmp/crash-20210516-195334-root-ica_aroma.a33.a0-4e2fde93-fcaa-42fe-885b-8bf871148856.pklz
Traceback (most recent call last):
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 12, in exec_ICA_AROMA
FileNotFoundError: [Errno 2] No such file or directory: '/outputsPreprocess/main_wf/confound_regression_wf/_scan_info_subject_id3546.session2_split_name_sub-3546_ses-2_T2w/_run_1/ica_aroma/aroma_out/denoised_func_data_nonaggr.nii.gz' -> '/outputsPreprocess/main_wf/confound_regression_wf/_scan_info_subject_id3546.session2_split_name_sub-3546_ses-2_T2w/_run_1/ica_aroma/aroma_out/sub-3546_ses-2_run-01_task-rest_bold_RAS_combined_aroma.nii.gz'
```

[rabies_confound_regression.log](https://github.com/CoBrALab/RABIES/files/6491475/rabies_confound_regression.log)

**Comment by Gab-D-G** [comment]
Hi, my appologies for the late reply. There has been a lot of updates lately, I would invite you to download the latest version 0.2.5, and run it again if the error is still persisting on your side. I am not running into these sorts of errors on my side. Let me know if it is still an issue, and I'll address it!

**Comment by ChristianNSchmitz** [comment]
Hey, we tried to run the updated version 0.2.5 which resulted in a different error (you can see the log attached). As we have a dataset with rats, the default parameter "mouse-preprocessing-v5.sh" was set to "thresh_reg" for --bold_bias_cor_method and --anat_bias_cor_method.
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/6616331/rabies_preprocess.log)

**Comment by Gab-D-G** [comment]
Hello Christian, I've never encountered this one before, and I tried to reproduce it on my side but I don't get the same error. It seems based on the error output that something is wrong with your image metadata. How do you generate your nifti inputs from the scanner?

**Comment by ChristianNSchmitz** [comment]
Hey Gabriel, I've used brkraw (https://github.com/brkraw/bruker) for the conversion. However, the analysis worked before and stopped at some later point.

**Comment by Gab-D-G** [comment]
Hi Christian, that's actually the converter I am also using. Would you mind sending us a sample of your raw data to try it out on our side? You could send it over to gabriel.desrosiers-gregoire@mail.mcgill.ca . That way I should be able to reproduce your error on my side.

**Comment by ChristianNSchmitz** [comment]
Hey Gabriel, I've sent you a link to my google drive. There you can find the *.pv file of one recording and the corresponding converted *.nii file (without the fieldmap). Thanks a lot for your support!

**Comment by Gab-D-G** [comment]
Hi, I have tried on my side and it seems like it has something to do with ANTs version, since the error arises in the singularity container, but not on my laptop. @gdevenyi any idea what this might be about?
```(base) gabriel@gabriel-XPS-13-7390:~/Work/dev/testing_rabies$ singularity shell -B ~/Work/resources/atlases/Fischer344_nii_v4/:/atlas -B $PWD:/work_dir rabies-0.2.5.sif
Singularity: Invoking an interactive shell within container...

Singularity rabies-0.2.5.sif:/home/gabriel/Work/dev/testing_rabies> antsMotionCorr -d 3 -o [ants_mc_tmp/motcorr,ants_mc_tmp/motcorr.nii.gz,ants_mc_tmp/motcorr_avg.nii.gz] -m MI[ /work_dir/christian_out/main_wf/bias_cor_bold_main_wf/gen_bold_ref/_scan_info_subject_id3449.session1.run1_split_name_sub-3449_ses-1_run-01_task-rest_bold/gen_ref/sub-3449_ses-1_run-01_task-rest_bold_RAS_bold_ref.nii.gz ,                 /work_dir/christian_out/main_wf/_scan_info_subject_id3449.session1.run1_split_name_sub-3449_ses-1_run-01_task-rest_bold/bold_convert_to_RAS/sub-3449_ses-1_run-01_task-rest_bold_RAS.nii.gz , 1 , 20 , regular, 0.2 ] -t Rigid[ 0.25 ] -i 50x20 -s 1x0 -f 2x1 -u 1 -e 1 -l 1 -n 10 -v 0
Exception caught during reference file reading 

itk::ExceptionObject (0x55f9baf2b280)
Location: "unknown" 
File: /opt/ANTs/build/ITKv5/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Line: 1972
Description: itk::ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

 file /work_dir/christian_out/main_wf/_scan_info_subject_id3449.session1.run1_split_name_sub-3449_ses-1_run-01_task-rest_bold/bold_convert_to_RAS/sub-3449_ses-1_run-01_task-rest_bold_RAS.nii.gz
Segmentation fault (core dumped)
Singularity rabies-0.2.5.sif:/home/gabriel/Work/dev/testing_rabies> 
```

**Comment by Gab-D-G** [comment]
```
(base) gabriel@gabriel-XPS-13-7390:~/Work/dev/testing_rabies$ PrintHeader christian_out/main_wf/_scan_info_subject_id3449.session1.run1_split_name_sub-3449_ses-1_run-01_task-rest_bold/bold_convert_to_RAS/sub-3449_ses-1_run-01_task-rest_bold_RAS.nii.gz
 Spacing [0.365018, 0.699806, 0.36494, 1.5]
 Origin [17.5525, 8.791, -17.8725, 0]
 Direction 
-0.999951 -0.00714483 -0.00822059 0
0.00547911 -0.997419 0.0712447 0
-0.00821883 0.0714483 0.997425 0
0 0 0 1

 Size : [96, 30, 96, 1450]

  Image Dimensions   : [96, 30, 96, 1450]
  Bounding Box       : {[17.5525 8.791 -17.8725 0], [52.5942 29.7852 17.1617 2175]}
  Voxel Spacing      : [0.365018, 0.699806, 0.36494, 1.5]
  Intensity Range    : [0.0256348, 73.5849]
  Mean Intensity     : 2.15082
  Direction Cos Mtx. : 
-0.999951 -0.00714483 -0.00822059 0
0.00547911 -0.997419 0.0712447 0
-0.00821883 0.0714483 0.997425 0
0 0 0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    bitpix = 16
    cal_max = 0
    cal_min = 0
    datatype = 4
    dim[0] = 4
    dim[1] = 96
    dim[2] = 30
    dim[3] = 96
    dim[4] = 1450
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    pixdim[0] = 1
    pixdim[1] = 0.365018
    pixdim[2] = 0.699806
    pixdim[3] = 0.36494
    pixdim[4] = 1.5
    pixdim[5] = 1
    pixdim[6] = 1
    pixdim[7] = 1
    qform_code = 0
    qform_code_name = NIFTI_XFORM_UNKNOWN
    qoffset_x = -17.5525
    qoffset_y = -8.791
    qoffset_z = -17.8725
    quatern_b = 0.0356973
    quatern_c = 0.00412193
    quatern_d = -0.00315375
    scl_inter = 36.8058
    scl_slope = 0.00112244
    sform_code = 2
    sform_code_name = NIFTI_XFORM_ALIGNED_ANAT
    slice_duration = 0.05
    slice_end = 29
    slice_start = 0
    srow_x = 0.365 0.005 0.00300002 -17.5525
    srow_y = -0.00199997 0.698 -0.026 -8.791
    srow_z = -0.00300002 0.05 0.364 -17.8725
    toffset = 0
    vox_offset = 352
(base) gabriel@gabriel-XPS-13-7390:~/Work/dev/testing_rabies$ 
```

**Comment by gdevenyi** [comment]
Have you tried running any other ANTs commands on the files inside the container? Does PrintHeader work?

**Comment by gdevenyi** [comment]
Also, if you think its an ANTs version, we should compare version numbers:
```
antsRegistration --version
```

**Comment by Gab-D-G** [comment]
PrintHeader does not work
```
Singularity rabies-0.2.5.sif:/home/gabriel/Work/dev/testing_rabies> PrintHeader /work_dir/christian_file/sub-3449_ses-1_run-01_task-rest_bold.nii
 cant read /work_dir/christian_file/sub-3449_ses-1_run-01_task-rest_bold.nii
S
```
```
Singularity rabies-0.2.5.sif:/home/gabriel/Work/dev/testing_rabies> antsRegistration --version
ANTs Version: 2.3.5.dev238-g1759e
Compiled: May 27 2021 01:24:52
```

```
(base) gabriel@gabriel-XPS-13-7390:~/Work/dev/testing_rabies$ antsRegistration --version
ANTs Version: 2.2.0.dev133-gc7310
Compiled: Oct  3 2020 08:58:39
```

**Comment by gdevenyi** [comment]
This error raising was introduced into ITK in this commit 15 months ago, due to the fact NIFTI cannot properly represent non-orthonormal direction cosines:

https://github.com/InsightSoftwareConsortium/ITK/commit/34231b57021418fdb6afd4fcf5082a73b12969ed

The scanner parameters being used may be the root cause of this. If you feel they are not, you should open up a bug on the ITK github and describe the issue.

**Comment by gdevenyi** [comment]
This could also be an issue with how the NIFTI files are generated by brkraw, but the root cause will remain some weird non-isotropic voxels which is a scanner configuration issue.

You may wish to also open a bug at https://github.com/BrkRaw/brkraw

**Comment by ChristianNSchmitz** [comment]
I habe been converting the dataset with heudiconv using dicoms instead of brkraw. However, I came across this error:
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/6809698/rabies_preprocess.log)

I noticed that "mouse-preprocessing-v5.sh" was chosen as default for bold_bias_cor_method for this rat dataset, could this be the reason for the error?
Thanks a lot and best wishes!

**Comment by Gab-D-G** [comment]
Hi Christian, I don't think this is due to mouse-preprocessing-v5.sh . It should still perform quite well with rats actually. It seems like something bugged during runtime because the errors are all over the place, and some of them don't have anything to do with the data (e.g. subprocess.CalledProcessError: Command 'mv ants_mc_tmp first_ants_mc_tmp' died with <Signals.SIGBUS: 7>. which simply renames a directory). Did you try running it a second time? Or using -p MultiProc?

**Comment by ChristianNSchmitz** [comment]
Hey Gabriel,
somehow the multiproc setting is crashing my terminal all the time (I'll attach the log file). I will re-try the linear option.
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/6830085/rabies_preprocess.log)

**Comment by ChristianNSchmitz** [comment]
Dear Gabriel,
unfortunately, running the preprocessing a seconds time with the linear option results in the same error:
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/6842477/rabies_preprocess.log)

**Comment by Gab-D-G** [comment]
Hi @ChristianNSchmitz , unfortunately, I can't figure what's causing this problem. It seems like it has something to go with the computing platform you might be using, since it seems to be stopping in the middle of various commands and the errors are not consistent. Are you running this on your laptop? I can't access the data you sent us earlier anymore, but if you want I can try again running it on my side to confirm whether it is a computer issue. I don't know if @gdevenyi would have any ideas here?

**Comment by gdevenyi** [comment]
I can tell from the prompt that this is being run in Windows Subsystem for Linux install, probably on laptop.

@ChristianNSchmitz do you have access to a proper workstation or compute cluster to run this computationally expensive pipeline?

**Comment by Gab-D-G** [comment]
@ChristianNSchmitz I think it would be helpful if you could try again with the test dataset that we recommend to test RABIES installation https://zenodo.org/record/3937697 . In principle, it should definitely work with this dataset.

**Comment by ChristianNSchmitz** [comment]
Dear Gabriel,
unfortunately, our workstations are restricted to Windows due to limitations of specific software, thus, we have to use Windows Subsystem for Linux as alternative. 
I am currently running rabies on the dataset again (without any other heavy load on the workstation,- it might have been an error of memory allocation). If that doesn't work, I will try the test dataset and I will run Rabies on a Linux based cluster.
I will let you know as soon as it's done!

**Comment by CMonnin** [comment]
Hello, closing this issue as it's been open for a long time. If you need more assistance please feel free to re-open this issue.
