### ISSUE TITLE
Seed_list isue?  Seed path doesn't exist?

### ISSUE THREAD

**Issue by geowk** [CoBrALab/RABIES#292]
Hello,

I'm running the analysis part of RABIES. Preprocessing and Confound correction worked fine.

The problem I'm having is with the --seed_list option for analysis.

I get the following message saying the seed provided doesn't exist, but the path is correct as well as the filename.

`Traceback (most recent call last):
  File "/home/rabies/miniforge/bin/rabies", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/rabies/RABIES/scripts/rabies", line 3, in <module>
    execute_workflow()
  File "/home/rabies/RABIES/rabies/run_main.py", line 48, in execute_workflow
    workflow = analysis(opts, log)
  File "/home/rabies/RABIES/rabies/run_main.py", line 278, in analysis
    workflow = init_main_analysis_wf(preprocess_opts, confound_correction_opts, opts)
  File "/home/rabies/RABIES/rabies/analysis_pkg/main_wf.py", line 50, in init_main_analysis_wf
    analysis_wf = init_analysis_wf(
  File "/home/rabies/RABIES/rabies/analysis_pkg/analysis_wf.py", line 45, in init_analysis_wf
    raise ValueError(
ValueError: Provide seed file path /data/roi/ACC_roi.nii.gz doesn't exists.`

`singularity run -B ${sigma_dir}/:${sigma_dir}/ \
	   -B  ${file_dir}/${input_dir}:/input_BIDS:ro \
	    -B  ${file_dir}/${preproc_dir}:/preprocess_outputs/ \
	    -B ${file_dir}/${confound_dir}:/confound_correction_outputs \
	    -B ${file_dir}/${analysis_dir}:/analysis_outputs \
	    ${file_dir}/rabies.sif \
	    -p MultiProc --local_threads 15 \
	    analysis /confound_correction_outputs /analysis_outputs  \
	     --seed_list /data/roi/ACC_roi.nii.gz  \
	    --group_ica apply=true,dim=0,random_seed=1`

Not sure what is happening. If I remove the  --seed_list line from the above rabies command, it runs fine.

g

**Comment by gdevenyi** [comment]
Please include the complete command you're running.

**Comment by geowk** [comment]
Hello,

This is the analysis command.

`singularity run -B ${sigma_dir}/:${sigma_dir}/ \
	   -B  ${file_dir}/${input_dir}:/input_BIDS:ro \
	    -B  ${file_dir}/${preproc_dir}:/preprocess_outputs/ \
	    -B ${file_dir}/${confound_dir}:/confound_correction_outputs \
	    -B ${file_dir}/${analysis_dir}:/analysis_outputs \
	    ${file_dir}/rabies.sif \
	    -p MultiProc --local_threads 15 \
	    analysis /confound_correction_outputs /analysis_outputs  \
	    --seed_list /data/roi/ACC_roi.nii.gz \
	    --group_ica apply=true,dim=0,random_seed=1 `


Here is what is printed to screen when I run the bash script
[analysis_error_printed_to_screen.txt](https://github.com/CoBrALab/RABIES/files/11790511/analysis_error_printed_to_screen.txt)


Here is the log file
[rabies_analysis_log.txt](https://github.com/CoBrALab/RABIES/files/11790494/rabies_analysis_log.txt)


This is the first attempt to run it seed-based correlation with the --seed_list option. I"ve run group_ica and DR_ICA optipns in the past  for the analysis command with no issues. We are running RABIES version 0.4.8.

g

**Comment by Gab-D-G** [comment]
Hi, it means the path to the file is not found with your current implementation of the container. Have you set a path to /data/roi ? Unless ${sigma_dir} corresponds to this, it has not been set. You can review our instructions on setting singularity paths with -B here https://rabies.readthedocs.io/en/stable/running_the_software.html#execution-syntax-with-containerized-installation-singularity-and-docker. Let us know if you have further questions.

**Comment by geowk** [comment]
Thanks,

Setting the path to /data/roi worked

`singularity run -B ${sigma_dir}/:${sigma_dir}/ \ -B  ${file_dir}/${input_dir}:/input_BIDS:ro \ -B  ${file_dir}/${preproc_dir}:/preprocess_outputs/ \ -B ${file_dir}/${confound_dir}:/confound_correction_outputs \ -B ${file_dir}/${analysis_dir}:/analysis_outputs \   -B /data/roi/:/data/roi/ \  ${file_dir}/rabies.sif \ -p MultiProc --local_threads 15 \ analysis /confound_correction_outputs /analysis_outputs  \ --seed_list /data/roi/ACC_roi.nii.gz \ --group_ica apply=true,dim=0,random_seed=1 `
