### ISSUE TITLE
Anatomical has to be nii.gz

### ISSUE THREAD

**Issue by egarza** [CoBrALab/RABIES#73]
The current program does not allow for *.nii files, only *.nii.gz for the anatomical images.

It would be nice if it could also be flexible with this.

Eduardo

**Comment by gdevenyi** [comment]
an you

**Comment by egarza** [comment]
Sure. Here is the file tree:

```
tree
.
├── sub-10
│   ├── ses-1
│   │   ├── anat
│   │   │   ├── sub-10_ses-1_pp.nii.gz
│   │   │   └── sub-10_ses-1_T2w.json
│   │   ├── fmap
│   │   │   ├── sub-10_ses-1_fieldmap.json
│   │   │   ├── sub-10_ses-1_fieldmap.nii.gz
│   │   │   └── sub-10_ses-1_magnitude.nii.gz
│   │   └── func
│   │       ├── sub-10_ses-1_task-rest_run-1_bold.json
│   │       └── sub-10_ses-1_task-rest_run-1_bold.nii.gz
│   └── ses-2
│       ├── anat
│       │   ├── sub-10_ses-2_pp.nii.gz
│       │   └── sub-10_ses-2_T2w.json
│       ├── fmap
│       │   ├── sub-10_ses-2_fieldmap.json
│       │   ├── sub-10_ses-2_fieldmap.nii.gz
│       │   └── sub-10_ses-2_magnitude.nii.gz
│       └── func
│           ├── sub-10_ses-2_task-rest_run-1_bold.json
│           └── sub-10_ses-2_task-rest_run-1_bold.nii.gz
├── sub-11
│   ├── ses-1
│   │   ├── anat
│   │   │   ├── sub-11_ses-1_pp.nii.gz
│   │   │   └── sub-11_ses-1_T2w.json
│   │   ├── fmap
│   │   │   ├── sub-11_ses-1_fieldmap.json
│   │   │   ├── sub-11_ses-1_fieldmap.nii.gz
│   │   │   └── sub-11_ses-1_magnitude.nii.gz
│   │   └── func
│   │       ├── sub-11_ses-1_task-rest_run-1_bold.json
│   │       └── sub-11_ses-1_task-rest_run-1_bold.nii.gz
│   └── ses-2
│       ├── anat
│       │   ├── sub-11_ses-2_pp.nii.gz
│       │   └── sub-11_ses-2_T2w.json
│       ├── fmap
│       │   ├── sub-11_ses-2_fieldmap.json
│       │   ├── sub-11_ses-2_fieldmap.nii.gz
│       │   └── sub-11_ses-2_magnitude.nii.gz
│       └── func
│           ├── sub-11_ses-2_task-rest_run-1_bold.json
│           └── sub-11_ses-2_task-rest_run-1_bold.nii.gz
└── sub-5
    ├── ses-1
    │   ├── anat
    │   │   ├── sub-5_ses-1_pp.nii.gz
    │   │   └── sub-5_ses-1_T2w.json
    │   ├── fmap
    │   │   ├── sub-5_ses-1_fieldmap.json
    │   │   ├── sub-5_ses-1_fieldmap.nii.gz
    │   │   └── sub-5_ses-1_magnitude.nii.gz
    │   └── func
    │       ├── sub-5_ses-1_task-rest_run-1_bold.json
    │       └── sub-5_ses-1_task-rest_run-1_bold.nii.gz
    └── ses-2
        ├── anat
        │   ├── sub-10_ses-1_pp.nii
        │   ├── sub-10_ses-2_pp.nii
        │   ├── sub-11_ses-1_pp.nii
        │   ├── sub-11_ses-2_pp.nii
        │   ├── sub-5_ses-1_pp.nii
        │   ├── sub-5_ses-2_pp.nii.gz
        │   └── sub-5_ses-2_T2w.json
        ├── fmap
        │   ├── sub-5_ses-2_fieldmap.json
        │   ├── sub-5_ses-2_fieldmap.nii.gz
        │   └── sub-5_ses-2_magnitude.nii.gz
        └── func
            ├── sub-5_ses-2_task-rest_run-1_bold.json
            └── sub-5_ses-2_task-rest_run-1_bold.nii.gz

27 directories, 47 files
```
Heres the call:

sudo docker run -it --rm -v /media/egarza/Elements2/projects/INB/GARZALAB/Pilotos/Prueba1/data:/nii_inputs:ro -v /media/egarza/Elements2/projects/INB/GARZALAB/Pilotos/Prueba1/derivatives/rabies:/outputs -v /home/egarza/atlases/Rat/Fischer344_nii_v3/Fischer344_nii_v3:/atlas gabdesgreg/rabies:latest /nii_inputs /outputs --tpattern seq --TR 2.1s --apply_despiking --disable_anat_preproc --anat_template /atlas/Fischer344_template.nii --brain_mask /atlas/Fischer344_mask.nii --WM_mask /atlas/Fischer344_TPM_WM.nii.gz --CSF_mask /atlas/Fischer344_TPM_CSF.nii.gz --vascular_mask /atlas/Fischer344_TPM_CSF.nii.gz --labels /atlas/Fischer344_labels_v3.nii

Here is the log:

[rabies.log](https://github.com/CoBrALab/RABIES/files/4822266/rabies.log)

The specific error was:

```
Traceback (most recent call last):
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/home/rabies/RABIES-0.1.2-dev/rabies/preprocess_bold_pkg/utils.py", line 75, in _run_interface
    raise ValueError('Error in '+command)
ValueError: Error in gzip /nii_inputs/sub-11/ses-1/anat/sub-11_ses-1_pp.nii
```

After I changed the files to gzip, this error disappeared.
